name: ğŸ“‹ Test All

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group: {}
  workflow_dispatch: {}

env:
  FORCE_COLOR: true

jobs:
  build-and-test:
    name: ğŸ“‹ Test on ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: ğŸ“¦ Checkout Repository
        uses: actions/checkout@v5

      - name: ğŸ—ï¸ Setup Node.js Environment
        uses: actions/setup-node@v5
        with:
          cache: npm
          cache-dependency-path: package-lock.json

      - name: ğŸ—ï¸ Setup project
        run: npm ci

      - name: ğŸ› ï¸ Build projects
        run: npm run compile

      - name: ğŸ“‹ Run Tests
        run: npm run test:all

      - name: ğŸ” Linting
        run: npm run lint
