name: ğŸšš Release IDE
on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  release-vscode:
    runs-on: ubuntu-latest
    name: ğŸ–¥ï¸ Release VSCode
    environment:
      name: 'Vscode Marketplace'
      url: https://marketplace.visualstudio.com/items?itemName=BlockceptionLtd.blockceptionvscodeminecraftbedrockdevelopmentextension
    steps:
      - name: ğŸ“¦ Checkout Repository
        uses: actions/checkout@v5

      - name: ğŸ—ï¸ Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version-file: .nvmrc

      - name: Setup Node Project
        run: npm install

      - name: ğŸ› ï¸ Build projects
        run: npm run compile

      - name: ğŸ› ï¸ Package
        working-directory: ${{github.workspace}}/ide/vscode
        run: |
          npx vsce package --no-dependencies --no-git-tag-version --out vscode-extension.vsix
          echo "Size of package: $(du -h *.vsix | cut -f1)" >> $GITHUB_STEP_SUMMARY

      - name: ğŸšš Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension
          path: '${{github.workspace}}/ide/vscode-extension.vsix'

      - name: ğŸ“¦ -> ğŸ¤ Upload to Vscode
        run: npx @vscode/vsce publish --packagePath ${{github.workspace}}/ide/vscode-extension.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCODE_KEY }}

