name: ğŸšš Release NPM Packages
on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  release-npm-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - bedrock-commands
          - bedrock-diagnoser
          - bedrock-project
          - bedrock-types
          - bedrock-vanilla-data
          - molang
          - packages/project
    steps:
      - name: ğŸ“¦ Checkout Repository
        uses: actions/checkout@v6

      - name: ğŸ—ï¸ Setup Node.js Environment
        uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: package-lock.json

      - name: ğŸ—ï¸ Setup project
        run: npm ci

      - name: ğŸ› ï¸ Build projects
        working-directory: '${{GITHUB.workspace}}/packages/${{matrix.package}}'
        run: npm run compile

      - name: ğŸ“‹ Run Tests
        run: npm run test

      - name: ğŸšš Publish package
        run: npm publish
