name: ğŸ¥„ Scraping data
env:
  FORCE_COLOR: true

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 */7 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: ğŸ¥„ Scraper
    steps:
      - name: ğŸ“¦ Checkout Repository
        uses: actions/checkout@v6

      - name: ğŸ—ï¸ Setup Node.js Environment
        uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: package-lock.json

      - name: ğŸ—ï¸ Setup project
        working-directory: tools/vanilla-scraper
        run: npm ci

      - name: ğŸ¥„ Scrape
        working-directory: tools/vanilla-scraper
        run: npm run scrape

      - name: ğŸ—’ï¸ Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          title: Scraped vanilla data update